[features]
seeds = false
skip-lint = false
[programs.localnet]
staking_program = "9adQNczpQc7f4QX1ZE597EXcmjzQZjwJV9vKJ1dPxBKu"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/solashi/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
